nelmio_api_doc:
    documentation:
        info:
            title: BileMo API
            description: Bilemo products and users management
            version: 1.0.0
        tags:
            - name: "Products"
              description: "Display information about products"
            - name: "Users"
              description: "Display information about users"
            - name: "Login"
              description: "Login's page"
    areas: # to filter documented areas
        default:
            path_patterns:
                - ^/(?!/doc$) # Accepts routes under /api except /api/doc
